version: "3.9"

services:

  postgres:
    image: postgres:14
    container_name: ota_postgres
    restart: always
    environment:
      POSTGRES_DB: ota_console
      POSTGRES_USER: ota_user
      POSTGRES_PASSWORD: ota_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ota_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://ota_user:ota_pass@postgres:5432/ota_console
      JWT_SECRET: supersecret
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: ota_frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://172.31.1.122:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: